// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Data.Entities
{
    public partial class Product
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public DateTime AddDate { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}