// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Data.Entities
{
    public partial class UserToken
    {
        public Guid RefreshToken { get; set; }
        public string AccessToken { get; set; }
        public int UserId { get; set; }
        public DateTime AddDate { get; set; }
        public DateTime? UpdateDate { get; set; }

        public virtual User User { get; set; }
    }
}